### ISSUE TITLE
rights for directories are set wrong

### ISSUE THREAD

**Issue by RubenKelevra** [SupraSummus/ipfs-api-mount#10]
I mounted a ipfs cid and made an `ls -l` in the directory.

The listing shows for every directory the followings rights and metadata:

```
dr--r--r-- 0 root root 0  1. Jan 1970 example
```

This is obviously wrong, a directory needs x rights for root, to be allowed to be changed into.

**Comment by SupraSummus** [comment]
thanks for reporting, will look at it soon

**Comment by RubenKelevra** [comment]
I've updated the aur package to the latest master version, and can confirm this is fixed :)
