### ISSUE TITLE
ipfsapi is outdated warning

### ISSUE THREAD

**Issue by RubenKelevra** [SupraSummus/ipfs-api-mount#4]
On start the latest version shows the following warning.

`/usr/lib/python3.8/site-packages/ipfs_api_mount/__init__.py:9: FutureWarning: The `ipfsapi` library is deprecated and will stop receiving updates on the 31.12.2019! If you are on Python 3.5+ please enable and fix all Python deprecation warnings (CPython flag `-Wd`) and switch to the new `ipfshttpclient` library name. Python 2.7 and 3.4 will not be supported by the new library, so please upgrade.`

**Comment by SupraSummus** [comment]
Thanks for the issue! I'll look at it soon.

**Comment by SupraSummus** [comment]
I've replaced `ipfsapi` with `ipfshttpclient` and done few other fixes. New version - 0.2.0 is out and uploaded to pypi.
